### ISSUE TITLE
no compile in kernel 5.6.0 fedora 32 beta

### ISSUE THREAD

**Issue by tester1969** [maccuaa/asus-ac53-rtl8822bu#4]
Does not compile with 5.6.0 kernel, so issue and no network, i got the error here it is:

  CC [M]  /var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/ioctl_cfg80211.o
/var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/ioctl_cfg80211.c: In function ‘cfg80211_rtw_change_iface’:
/var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/ioctl_cfg80211.c:2365:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
 2365 |   is_p2p = _TRUE;
/var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/ioctl_cfg80211.c:2367:2: note: here
 2367 |  case NL80211_IFTYPE_STATION:
      |  ^~~~
/var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/ioctl_cfg80211.c:2389:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
 2389 |   is_p2p = _TRUE;
/var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/ioctl_cfg80211.c:2391:2: note: here
 2391 |  case NL80211_IFTYPE_AP:
      |  ^~~~
  CC [M]  /var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/wifi_regd.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/rtw_android.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/rtw_proc.o
/var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/rtw_proc.c: In function ‘rtw_proc_create_entry’:
/var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/rtw_proc.c:70:71: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   70 |  entry = proc_create_data(name,  S_IFREG | S_IRUGO | S_IWUGO, parent, fops, data);
      |                                                                       ^~~~
      |                                                                       |
      |                                                                       const struct file_operations *
In file included from /var/lib/dkms/rtl88x2bu/5.3.1/build/include/../os_dep/linux/rtw_proc.h:18,
                 from /var/lib/dkms/rtl88x2bu/5.3.1/build/include/osdep_intf.h:128,
                 from /var/lib/dkms/rtl88x2bu/5.3.1/build/include/drv_types.h:105,
                 from /var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/rtw_proc.c:17:
./include/linux/proc_fs.h:61:13: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
   61 |             const struct proc_ops *,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:268: /var/lib/dkms/rtl88x2bu/5.3.1/build/os_dep/linux/rtw_proc.o] Error 1
make[1]: *** [Makefile:1683: /var/lib/dkms/rtl88x2bu/5.3.1/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.6.0-0.rc5.git0.2.fc32.x86_64'
make: *** [Makefile:2011: modules] Error 2

**Comment by tester1969** [comment]
I changed the code and now compiles fine. I also created a fork from another thread
