### ISSUE TITLE
Fails to compile with kernel-5.2.5-200.fc30.x86_64

### ISSUE THREAD

**Issue by bradfordcp** [maccuaa/asus-ac53-rtl8822bu#1]
```
/home/bradfordcp/src/asus-ac53-rtl8822bu/os_dep/linux/os_intfs.c:1431:22: error: initialization of ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_device *)’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *)’} from incompatible pointer type ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))’} [-Werror=incompatible-pointer-types]
 1431 |  .ndo_select_queue = rtw_select_queue,
      |                      ^~~~~~~~~~~~~~~~
```

**Comment by bradfordcp** [comment]
[build.log](https://github.com/maccuaa/asus-ac53-rtl8822bu/files/3477924/build.log)
Attached the complete `build.log` which was made with `make 2>&1 | tee build.log`

**Comment by maccuaa** [comment]
Thanks for raising the issue. I'll take a look at this tonight.

**Comment by bradfordcp** [comment]
For what it's worth your commit fixed my issue. This is now up and stable through `kernel-5.2.7-200`
